# Generated by Django 2.0.5 on 2018-05-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appid',
            fields=[
                ('appid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('appsecret', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_appid',
            },
        ),
    ]
