# Generated by Django 2.0.1 on 2018-04-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsj',
            fields=[
                ('TM', models.CharField(max_length=400, verbose_name='题名')),
                ('ZRZ', models.CharField(max_length=400, verbose_name='责任者')),
                ('ISBN', models.CharField(max_length=160, null=True, verbose_name='ISBN号')),
                ('CBS', models.CharField(max_length=400, null=True, verbose_name='出版社')),
                ('CBRQ', models.CharField(max_length=40, null=True, verbose_name='出版日期')),
                ('JGRQ', models.CharField(max_length=10, verbose_name='荐购日期')),
                ('DGZT', models.CharField(help_text='订购状态 0未处理 1已订购 2不订购 3退订', max_length=1, null=True, verbose_name='订购状态')),
                ('HFZT', models.CharField(help_text='回复状态 0未回复 1已回复', max_length=1, null=True, verbose_name='回复状态')),
                ('DCZT', models.CharField(max_length=1, null=True, verbose_name='典藏状态')),
                ('CLSM', models.CharField(max_length=4000, null=True, verbose_name='处理说明')),
                ('SFRZH', models.CharField(max_length=20, verbose_name='身份认证号(同证件号,学号/教工号)')),
                ('JGID', models.CharField(max_length=90, primary_key=True, serialize=False, verbose_name='荐购记录ID')),
                ('UPD', models.DateField(null=True, verbose_name='记录日期')),
            ],
            options={
                'verbose_name': '预订图书',
                'verbose_name_plural': '图书',
                'db_table': 'DSJ_TS_DZJG',
            },
        ),
        migrations.CreateModel(
            name='Js',
            fields=[
                ('XN', models.CharField(max_length=18, verbose_name='学年')),
                ('XQ', models.CharField(max_length=40, verbose_name='学期')),
                ('JSBH', models.CharField(max_length=10, verbose_name='教室编号')),
                ('XQJ', models.CharField(max_length=40, verbose_name='星期几')),
                ('SJD', models.IntegerField(help_text='1表示第1节课开始,3表示第三节开始', verbose_name='时间点')),
                ('DSZ', models.CharField(max_length=6, verbose_name='单双周')),
                ('QSZ', models.IntegerField(verbose_name='起始周')),
                ('JSZ', models.IntegerField(verbose_name='结束周')),
                ('SKCD', models.IntegerField(help_text='2表示2节,3表示3节', verbose_name='上课长度')),
                ('XKKH', models.CharField(max_length=100, verbose_name='选课课号')),
                ('JSZGH', models.CharField(max_length=20, verbose_name='教师职工号')),
                ('BZ', models.CharField(max_length=400, verbose_name='备注')),
                ('PK', models.CharField(max_length=4, verbose_name='课表来源')),
                ('GUID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('JSMC', models.CharField(max_length=40, verbose_name='教室名称')),
                ('UPD', models.DateField(max_length=7, verbose_name='更新时间')),
                ('KCZWMC', models.CharField(max_length=460, verbose_name='课程中文名')),
                ('KCYWMC', models.CharField(max_length=460, verbose_name='课程英文名')),
            ],
            options={
                'verbose_name': '教学场地/教师表',
                'verbose_name_plural': '教学场地/教师表',
                'db_table': 'DSJ_JW_KB_JXCD_JS',
                'permissions': (('is_teacher', '教师权限'),),
            },
        ),
        migrations.CreateModel(
            name='tes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=255, null=True)),
                ('book_name', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Xs',
            fields=[
                ('XN', models.CharField(max_length=18, verbose_name='学年')),
                ('XQ', models.CharField(max_length=40, verbose_name='学期')),
                ('XH', models.CharField(max_length=20, verbose_name='学号')),
                ('XKKH', models.CharField(max_length=100, verbose_name='选课课号')),
                ('XQJ', models.CharField(max_length=40, verbose_name='星期几')),
                ('DJJ', models.IntegerField(verbose_name='第几节')),
                ('SKCD', models.IntegerField(help_text='2表示2节,3表示3节', verbose_name='上课长度')),
                ('DSZ', models.CharField(max_length=6, verbose_name='单双周')),
                ('QSZ', models.IntegerField(verbose_name='起始周')),
                ('JSZ', models.IntegerField(verbose_name='结束周')),
                ('KCB', models.CharField(max_length=200, verbose_name='课程表')),
                ('XKCS', models.CharField(max_length=50)),
                ('XSF', models.CharField(max_length=1, verbose_name='选上否')),
                ('GUID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('KCZWMC', models.CharField(max_length=460, verbose_name='课程中文名')),
                ('KCYWMC', models.CharField(max_length=460, verbose_name='课程英文名')),
            ],
            options={
                'verbose_name': '学生课表',
                'verbose_name_plural': '学生课表',
                'db_table': 'DSJ_JW_KB_XSKCB',
            },
        ),
    ]
