# Generated by Django 2.0.5 on 2018-05-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKctj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XN', models.CharField(max_length=50, verbose_name='原学年')),
                ('YZC', models.CharField(max_length=5, verbose_name='原周次')),
                ('YXQJ', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '全局调课',
                'verbose_name_plural': '全局调课',
                'db_table': 'GLOBAL_KCTJ',
            },
        ),
        migrations.CreateModel(
            name='JsAccount',
            fields=[
                ('ACCOUNT', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=255)),
                ('EMPLOYEETYPE', models.CharField(max_length=255)),
                ('SEX', models.CharField(max_length=255)),
                ('DEPARTMENT', models.CharField(max_length=255)),
                ('COLLEGENAME', models.CharField(max_length=255)),
                ('PRONAME', models.CharField(max_length=255)),
                ('GRADENAME', models.CharField(max_length=255)),
                ('CLASSNAME', models.CharField(max_length=255)),
                ('DQZT', models.CharField(max_length=255)),
                ('SYNCTIME', models.DateField()),
            ],
            options={
                'verbose_name': '人员信息表',
                'verbose_name_plural': '人员信息表',
                'db_table': 'USERINFO',
            },
        ),
        migrations.CreateModel(
            name='Rq',
            fields=[
                ('XN', models.CharField(max_length=10, verbose_name='学年')),
                ('XQ', models.CharField(max_length=2, verbose_name='学期')),
                ('N', models.IntegerField(verbose_name='年')),
                ('Y', models.IntegerField(verbose_name='月')),
                ('R', models.IntegerField(verbose_name='日')),
                ('DJZ', models.IntegerField(verbose_name='第几周')),
                ('XQJ', models.IntegerField(verbose_name='星期几')),
                ('NYR', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='年月日')),
                ('SFDYC', models.CharField(max_length=1, null=True, verbose_name='是否第一次')),
                ('ZC', models.IntegerField(null=True, verbose_name='')),
                ('ZC1', models.IntegerField(null=True, verbose_name='')),
                ('DJZ1', models.IntegerField(null=True, verbose_name='')),
                ('JJMC', models.CharField(max_length=20, null=True, verbose_name='节假日名称')),
            ],
            options={
                'verbose_name': '日期周次及节假日对应表',
                'verbose_name_plural': '日期周次及节假日对应表',
                'db_table': 'DSJ_JW_KB_RQKSZB',
            },
        ),
        migrations.CreateModel(
            name='Tt',
            fields=[
                ('BDLB', models.CharField(max_length=16, verbose_name='099变动类别')),
                ('BDBH', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='099变动编号')),
                ('XKKH', models.CharField(max_length=40, verbose_name='099选课课号')),
                ('YJSZGH', models.CharField(max_length=10, verbose_name='099原教师职工号')),
                ('YQSZ', models.IntegerField(verbose_name='099原起始周')),
                ('YJSZ', models.IntegerField(verbose_name='099原结束周')),
                ('YXQJ', models.CharField(max_length=2, verbose_name='099原星期几')),
                ('YSJD', models.CharField(max_length=2, verbose_name='099原时间段')),
                ('YDSZ', models.CharField(max_length=4, verbose_name='099原单双周')),
                ('YSKCD', models.CharField(max_length=2, verbose_name='099原上课长度')),
                ('YJSBH', models.CharField(max_length=10, verbose_name='099原教室编号')),
                ('XJSZGH', models.CharField(max_length=10, verbose_name='099现教师职工号')),
                ('XQSZ', models.IntegerField(verbose_name='099现起始周')),
                ('XJSZ', models.IntegerField(verbose_name='099现结束周')),
                ('XXQJ', models.CharField(max_length=2, verbose_name='099现星期几')),
                ('XSJD', models.CharField(max_length=2, verbose_name='099现时间段')),
                ('XDSZ', models.CharField(max_length=4, verbose_name='099现单双周')),
                ('XSKCD', models.CharField(max_length=2, verbose_name='099现上课长度')),
                ('XJSBH', models.CharField(max_length=10, verbose_name='099现教室编号')),
                ('JSSFYXBD', models.CharField(max_length=4, verbose_name='099允许变教室')),
                ('JSLB', models.CharField(max_length=50, verbose_name='099教室类别')),
                ('ZWS', models.CharField(max_length=4, verbose_name='099座位数')),
                ('XQYQ', models.CharField(max_length=4, verbose_name='099校区要求')),
                ('BDYY', models.CharField(max_length=160, verbose_name='099变动原因')),
                ('SQSJ', models.CharField(max_length=20, verbose_name='099申请时间')),
                ('SQR', models.CharField(max_length=20, verbose_name='099申请人')),
                ('SHBJ', models.CharField(max_length=2, verbose_name='099审核标记')),
                ('SHSJ', models.CharField(max_length=20, verbose_name='099审核时间')),
                ('SHR', models.CharField(max_length=20, verbose_name='099审核人')),
                ('JCJG', models.CharField(max_length=100, verbose_name='')),
                ('QBQZZ', models.CharField(max_length=4, verbose_name='099标志')),
                ('YYLB', models.CharField(max_length=80, verbose_name='')),
                ('SFJLZHXS', models.CharField(max_length=2, verbose_name='099是否记录调停课总学时')),
                ('XYSHBJ', models.CharField(max_length=8, verbose_name='099学院审核标记 ')),
                ('XYSHSJ', models.CharField(max_length=20, verbose_name='099学院审核时间 ')),
                ('XYSHR', models.CharField(max_length=20, verbose_name='099学院审核人 ')),
                ('KC', models.CharField(max_length=4, verbose_name='')),
            ],
            options={
                'verbose_name': '调停课信息表',
                'verbose_name_plural': '调停课信息表',
                'db_table': 'DSJ_JW_KB_TTKXXB',
            },
        ),
        migrations.AlterField(
            model_name='xs',
            name='KCB',
            field=models.CharField(max_length=200, null=True, verbose_name='课程表'),
        ),
        migrations.AlterField(
            model_name='xs',
            name='KCYWMC',
            field=models.CharField(max_length=460, null=True, verbose_name='课程英文名'),
        ),
        migrations.AlterField(
            model_name='xs',
            name='KCZWMC',
            field=models.CharField(max_length=460, null=True, verbose_name='课程中文名'),
        ),
        migrations.AlterField(
            model_name='xs',
            name='XKCS',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xs',
            name='XSF',
            field=models.CharField(max_length=1, null=True, verbose_name='选上否'),
        ),
    ]
